### ISSUE TITLE
android scroll is not smoth?

### ISSUE THREAD

**Issue by ios-dev-newbie** [ascoders/react-native-image-zoom#46]
I have a flat list. Inside of that flat list I have added the image zoom view. This is working perfectly in iOS. where as in android when I tried to swipe the page to view the next image the view get stuck.

I have to do lot of swipe to actually swipe the image. I feel that in android the scroll is not smooth.

Please let me know how to add the smooth scroll to view.

**Comment by mohammedibrahim** [comment]
@ios-dev-newbie Did you find any solution for this issue ?

**Comment by ios-dev-newbie** [comment]
@mohammedibrahim  Sorry, I didn't get time to do research on it. But feel free to look at this solutions.
https://github.com/facebook/react-native/issues/9836#issuecomment-379043158. I hope it works fro you. Let me know if you find anything else.

**Comment by yurnery** [comment]
face the same problem, if anyone have solutions, please at me

**Comment by ascoders** [comment]
@marconett that's great! And i just released a new version `2.2.15`.

**Comment by ascoders** [comment]
`react-native-image-zoom-viewer` `2.2.15`

`react-native-image-pan-zoom` `2.1.8`

**Comment by hanishcodebrew** [comment]
Hi @ascoders , I am still facing this issue in Android, I have a home screen like Instagram, when I scroll down the list it works well in iOS, but in Android when I scroll the list specially, the image on which I am using your code, list does not scroll. I am using the latest version of your package
"react-native-image-pan-zoom": "^2.1.11",

renderToHardwareTextureAndroid is already there in your file mentioned above by @marconett . But no help.

Please assist me.

**Comment by joshuagish** [comment]
FYI, setting `renderToHardwareTextureAndroid={true}` causes Android 6 and Android 7 devices to crash. My image was 2500px by 3000px so maybe that was too much for the GPU to hold in memory in these older phones.

**Comment by aibrahim3546** [comment]
> I'm using `Animated.View` to make smooth scroll, but it seems not perfect in android. Can anyone help?

How did you manage to do with `Animated.View`

**Comment by ahmadAlMezaal** [comment]
Thanks for the suggestion @marconett, but adding the prop **renderToHardwareTextureAndroid={true}**  didn't solve the problem. Images zoom and scroll perfectly in a FlatList on IOS but when I put my fingers on the image to scroll on Android, it's not working...


Any suggestions, please?

**Comment by rahmanharoon** [comment]
I'm using ImageZoom inside a FlatList and I couldn't scroll images on android but working fine on ios. Is their any suggestions please. I changed renderToHardwareTextureAndroid={true} but didnt work fine
